### ISSUE TITLE
Updating custom metadata fields

### ISSUE THREAD

**Issue by LeapingLue** [thekoc/devonthink-python#1]
Hi there,
thanks so much for this great contribution that works nearly seamlessly so far.

One thing that I've noticed is that updating the dict for Custom MetaData-Attritbutes does not seem to work.

Assuming I've got a custom meta field called "NameDate" this should work and doest (btw) return the value I set in DevonThink while not returning the new value after adjusting it. Do you have any idea why that is?

```
from pydt3 import DEVONthink3

dtp3 = DEVONthink3()

inbox = dtp3.inbox

# get selected records
records = dtp3.selected_records

print(records[0].custom_meta_data["mdnamedate"])
records[0].custom_meta_data["mdnamedate"] = "newvaalue"
print(records[0].custom_meta_data["mdnamedate"])
```

**Comment by thekoc** [comment]
I'm looking into this

**Comment by thekoc** [comment]
> Hi there, thanks so much for this great contribution that works nearly seamlessly so far.
> 
> One thing that I've noticed is that updating the dict for Custom MetaData-Attritbutes does not seem to work.
> 
> Assuming I've got a custom meta field called "NameDate" this should work and doest (btw) return the value I set in DevonThink while not returning the new value after adjusting it. Do you have any idea why that is?
> 
> ```
> from pydt3 import DEVONthink3
> 
> dtp3 = DEVONthink3()
> 
> inbox = dtp3.inbox
> 
> # get selected records
> records = dtp3.selected_records
> 
> print(records[0].custom_meta_data["mdnamedate"])
> records[0].custom_meta_data["mdnamedate"] = "newvaalue"
> print(records[0].custom_meta_data["mdnamedate"])
> ```

Sorry for the late reply. Can you tryout if it is working now?

Remember to run `pip install --upgrade pydt3` beforehand.

Also note that the DEVONthink implementation does not allow you to add new field with spaces in AppleScript, see discussion here:

https://discourse.devontechnologies.com/t/how-to-modify-a-custom-field-value-using-applescript/64384/10

And noted sometimes it will automatic prepend  the `md` prefix to your keys.

**Comment by LeapingLue** [comment]
Yes, it does now work, thanks a lot! 

By the way: I do not get why `records[0]` is not equivalent to the first (or any) of the selected records. In fact it will return a completely different (unselected) entry. Not really an issue but something I've noticed.

**Comment by thekoc** [comment]
> Yes, it does now work, thanks a lot!
> 
> By the way: I do not get why `records[0]` is not equivalent to the first (or any) of the selected records. In fact it will return a completely different (unselected) entry. Not really an issue but something I've noticed.

> Yes, it does now work, thanks a lot!
> 
> By the way: I do not get why `records[0]` is not equivalent to the first (or any) of the selected records. In fact it will return a completely different (unselected) entry. Not really an issue but something I've noticed.

Do you have multiple DEVONthink windows opening? It may because that it is returning the selected record from the other window. If that's not the case,  I'd be really appreciated if you could provide more information in a new issue.
