### ISSUE TITLE
Run the script in DT

### ISSUE THREAD

**Issue by masonfocus** [thekoc/devonthink-python#3]
Hi, I'm experimenting with your example script and it works perfectly. Is there a way to run it from DT directly?

I tried to run an AppleScript but it give nothing at all.

It might be a problem with the `records = dtp.selected_records` part. 

Is there a way to run the script inside DT?

```applescript
on performSmartRule(theRecords)
	tell application id "DNtp"
		-- Specify the path to your Python script
		set pythonScriptPath to "path to it"
		try
			set processedContent to do shell script "/usr/bin/python3 " & quoted form of pythonScriptPath
			if scriptOutput is not "" then
				display alert "Script Output: " & processedContent
			else
				display alert "No output from script"
			end if
		on error errorMessage
			display alert "Error: " & errorMessage
		end try
	end tell
end performSmartRule
```

The reason I did't use your packed script is that I want to make modifications to the endpoint of api and update the completion code in accordance with the newest version of openai. 

If there is a way to just launch the script inside it would be great, otherwise it is still good enough to run it with a shortcut.

**Comment by thekoc** [comment]
Hi,

I've tested running the script within the smart rule, and it works as expected. Could you please provide more detailed information?
 
## Python script
```python
from pydt3 import DEVONthink3

dtp3 = DEVONthink3()
print(list(dtp3.selected_records))
r = dtp3.databases[0].records[0]
dtp3.open_window_for(r)
```


## Smart Rule
```applescript
on performSmartRule(theRecords)
	tell application id "DNtp"
		-- Specify the path to your Python script
		set pythonScriptPath to "path to it"
		try
			set processedContent to do shell script "/opt/homebrew/Caskroom/miniconda/base/bin/python3 /Users/thekoc/Developer/Temp/test.py"
			if processedContent is not "" then
				display alert "Script Output: " & processedContent
			else
				display alert "No output from script"
			end if
		on error errorMessage
			display alert "Error: " & errorMessage
		end try
	end tell
end performSmartRule
```

## Result
![CleanShot-2024-07-01@11 36 44@2x](https://github.com/thekoc/devonthink-python/assets/15809388/1b93000d-a289-462b-94a3-73edf74841f9)
